import {FormEvent,useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,Edit3,KeyRound,Plus,RefreshCw,Search,ShieldCheck,UserCog,Users} from 'lucide-react';
import {consoleApi} from '../consoleApi';

const ROLES=['SUPER_ADMIN','ADMIN','SUPPORT','MODERATOR','FINANCE','VIEWER'];

export function AdminUsersPage(){
 const[data,setData]=useState<any>(null),[detail,setDetail]=useState<any>(null),[edit,setEdit]=useState<any>(null),[search,setSearch]=useState(''),[role,setRole]=useState(''),[error,setError]=useState('');
 const load=async()=>{setError('');try{setData(await consoleApi.admins({search,role:role||undefined}))}catch(e){setError(e instanceof Error?e.message:'Unable to load admin users')}};
 useEffect(()=>{load()},[]);
 if(edit)return <AdminEditor admin={edit==='new'?null:edit} back={()=>setEdit(null)} done={async()=>{setEdit(null);await load()}}/>;
 if(detail)return <AdminDetail id={detail} back={()=>setDetail(null)} edit={(a:any)=>setEdit(a)} after={load}/>;
 return <div className="modulePage">
  <div className="moduleHero"><div><p className="eyebrow">MODULE 17 · ADMIN ACCESS CONTROL</p><h1>Admin Users & Roles</h1><p>Manage Universal Live control-center accounts, roles, permissions, lock state and password resets. Admin authentication remains separate from mobile user authentication.</p></div><div className="actionRow"><button className="secondaryBtn" onClick={load}><RefreshCw/> Refresh</button><button className="primarySmall" onClick={()=>setEdit('new')}><Plus/> Add admin</button></div></div>
  {error&&<div className="notice">{error}</div>}
  <div className="metricStrip"><Mini label="Admins" value={data?.metrics?.total||0}/><Mini label="Active" value={data?.metrics?.active||0}/><Mini label="Locked" value={data?.metrics?.locked||0}/><Mini label="Super admins" value={data?.metrics?.superAdmins||0}/></div>
  <div className="toolbar supportToolbar"><label className="tableSearch"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or email…"/><button className="textBtn" onClick={load}>Search</button></label><select value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option>{ROLES.map(r=><option key={r}>{r}</option>)}</select><button className="secondaryBtn" onClick={load}>Apply</button></div>
  <div className="panel userPanel"><div className="utr adminUserRow uth"><span>Administrator</span><span>Role</span><span>Status</span><span>Last login</span><span>Created</span><span></span></div>{(data?.items||[]).length===0?<div className="emptyState"><Users/><h3>No admin accounts</h3><p>No admin users match the current filters.</p></div>:(data.items||[]).map((x:any)=><div className="utr adminUserRow" key={x.id}><span className="userCell"><i>{String(x.display_name||x.email||'A')[0].toUpperCase()}</i><em><b>{x.display_name}</b><small>{x.email}</small></em></span><span><span className="planBadge">{x.role}</span></span><span><span className={'statusTag '+(x.is_active&&!x.is_locked?'ok':'off')}><i/>{!x.is_active?'Disabled':x.is_locked?'Locked':'Active'}</span></span><span>{x.last_login_at?new Date(x.last_login_at).toLocaleString():'Never'}</span><span>{new Date(x.created_at).toLocaleDateString()}</span><button className="iconBtn" onClick={()=>setDetail(x.id)}><UserCog/></button></div>)}</div>
 </div>
}
function Mini({label,value}:{label:string;value:number}){return <div className="miniMetric"><span>{label}</span><b>{Number(value||0).toLocaleString()}</b></div>}

function AdminEditor({admin,back,done}:{admin:any;back:()=>void;done:()=>void}){
 const[form,setForm]=useState<any>({email:admin?.email||'',displayName:admin?.display_name||'',role:admin?.role||'VIEWER',permissions:JSON.stringify(admin?.permissions||[],null,2),password:'',isActive:admin?.is_active??true}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{let permissions:any=[];try{permissions=JSON.parse(form.permissions||'[]')}catch{throw new Error('Permissions must be valid JSON')}if(!Array.isArray(permissions))throw new Error('Permissions must be a JSON array');const body={email:form.email,displayName:form.displayName,role:form.role,permissions,isActive:form.isActive,...(!admin?{password:form.password}:{})};if(admin)await consoleApi.updateAdminUser(admin.id,body);else await consoleApi.createAdminUser(body);await done()}catch(e){setError(e instanceof Error?e.message:'Unable to save admin')}finally{setBusy(false)}};
 return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back to admin users</button><div className="moduleHero"><div><p className="eyebrow">{admin?'EDIT ADMIN':'ADD ADMIN'}</p><h1>{admin?'Update administrator':'Create administrator'}</h1><p>Use least-privilege roles. SUPER_ADMIN can manage other admin accounts and global settings.</p></div></div>{error&&<div className="notice">{error}</div>}<form className="panel formPanel" onSubmit={submit}><div className="formGrid"><label><span>Email</span><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><span>Display name</span><input required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label><span>Role</span><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{ROLES.map(r=><option key={r}>{r}</option>)}</select></label>{!admin&&<label><span>Initial password</span><input type="password" required minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>}<label className="toggle"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/><i/><span>Account active</span></label><label style={{gridColumn:'1/-1'}}><span>Permissions JSON array</span><textarea className="jsonEditor" rows={8} value={form.permissions} onChange={e=>setForm({...form,permissions:e.target.value})}/></label></div><div className="formActions"><button type="button" className="secondaryBtn" onClick={back}>Cancel</button><button className="primarySmall" disabled={busy}><ShieldCheck/> Save admin</button></div></form></div>
}

function AdminDetail({id,back,edit,after}:{id:string;back:()=>void;edit:(a:any)=>void;after:()=>void}){
 const[data,setData]=useState<any>(null),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{setData(await consoleApi.adminUser(id))}catch(e){setError(e instanceof Error?e.message:'Unable to load admin')}};
 useEffect(()=>{load()},[id]);
 const toggle=async()=>{setBusy(true);try{await consoleApi.setAdminActive(id,!data.admin.is_active);await load();await after()}catch(e){setError(e instanceof Error?e.message:'Unable to update status')}finally{setBusy(false)}};
 const reset=async()=>{if(password.length<10){setError('Password must be at least 10 characters');return}setBusy(true);try{await consoleApi.resetAdminPassword(id,password);setPassword('');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to reset password')}finally{setBusy(false)}};
 if(!data)return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back</button>{error?<div className="notice">{error}</div>:<div className="emptyState"><UserCog/><h3>Loading administrator…</h3></div>}</div>;
 const a=data.admin;
 return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back to admin users</button><div className="moduleHero"><div><p className="eyebrow">ADMIN DETAIL</p><h1>{a.display_name}</h1><p>{a.email}</p></div><div className="actionRow"><button className="secondaryBtn" onClick={toggle} disabled={busy}>{a.is_active?'Disable':'Enable'}</button><button className="primarySmall" onClick={()=>edit(a)}><Edit3/> Edit</button></div></div>{error&&<div className="notice">{error}</div>}<div className="detailGrid"><section className="panel"><h3>Access</h3><Info k="Role" v={a.role}/><Info k="Active" v={a.is_active?'Yes':'No'}/><Info k="Locked until" v={a.locked_until?new Date(a.locked_until).toLocaleString():'Not locked'}/><Info k="Failed logins" v={a.failed_login_count}/><Info k="Last login" v={a.last_login_at?new Date(a.last_login_at).toLocaleString():'Never'}/></section><section className="panel"><h3>Permissions</h3><div className="jsonBlock">{JSON.stringify(a.permissions||[],null,2)}</div></section></div><section className="panel formPanel membershipEdit"><h3>Reset admin password</h3><p className="panelHint">This revokes all refresh tokens for this admin.</p><div className="passwordResetRow"><input type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} placeholder="New secure password"/><button className="primarySmall" onClick={reset} disabled={busy||password.length<10}><KeyRound/> Reset password</button></div></section><section className="panel"><div className="panelHead"><div><h3>Recent audit activity</h3><p>Actions performed by this administrator</p></div></div>{(data.recentAudit||[]).map((x:any)=><div className="recordLine" key={x.id}><span><b>{x.action}</b><small>{x.target_type||'system'} · {x.target_id||'—'}</small></span><span>{new Date(x.created_at).toLocaleString()}</span></div>)}</section></div>
}
function Info({k,v}:{k:string;v:any}){return <div className="info"><small>{k}</small><span>{v??'—'}</span></div>}
