import {FormEvent,useEffect,useState} from 'react';
import {CheckCircle2,RefreshCw,Settings,ShieldCheck,UserCog} from 'lucide-react';
import {consoleApi} from '../consoleApi';

export function AdminSettingsPage(){
 const[data,setData]=useState<any>(null),[profile,setProfile]=useState<any>({}),[prefs,setPrefs]=useState<any>({}),[global,setGlobal]=useState<any>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const load=async()=>{setError('');try{const[d,g]=await Promise.all([consoleApi.adminSettings(),consoleApi.globalAdminSettings()]);setData(d);setProfile({displayName:d.admin.display_name,email:d.admin.email});setPrefs({sidebarCollapsed:!!d.preferences?.sidebar_collapsed,tableDensity:d.preferences?.table_density||'comfortable',timezone:d.preferences?.timezone||'',preferences:JSON.stringify(d.preferences?.preferences||{},null,2)});setGlobal(g.settings||{})}catch(e){setError(e instanceof Error?e.message:'Unable to load settings')}};
 useEffect(()=>{load()},[]);
 const saveProfile=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setSaved('');try{await consoleApi.updateAdminProfile(profile);setSaved('Profile saved');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save profile')}finally{setBusy(false)}};
 const savePrefs=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setSaved('');try{let p={};try{p=JSON.parse(prefs.preferences||'{}')}catch{throw new Error('Preferences JSON is invalid')}await consoleApi.updateAdminPreferences({...prefs,preferences:p});setSaved('Preferences saved');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save preferences')}finally{setBusy(false)}};
 const saveGlobal=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setSaved('');try{await consoleApi.updateGlobalAdminSettings(global);setSaved('Global admin settings saved');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save global settings')}finally{setBusy(false)}};
 return <div className="modulePage"><div className="moduleHero"><div><p className="eyebrow">MODULE 19 · ADMIN SETTINGS</p><h1>Settings</h1><p>Administrator profile, control-center preferences, and SUPER_ADMIN-only global admin configuration. No mobile user settings are modified.</p></div><button className="secondaryBtn" onClick={load}><RefreshCw/> Reload</button></div>{error&&<div className="notice">{error}</div>}{saved&&<div className="successNotice"><CheckCircle2/>{saved}</div>}
 <div className="settingsGrid">
  <form className="panel formPanel" onSubmit={saveProfile}><div className="settingsTitle"><UserCog/><div><h3>My admin profile</h3><p>Identity used inside the control center.</p></div></div><div className="formGrid one"><label><span>Display name</span><input value={profile.displayName||''} onChange={e=>setProfile({...profile,displayName:e.target.value})}/></label><label><span>Email</span><input type="email" value={profile.email||''} onChange={e=>setProfile({...profile,email:e.target.value})}/></label><label><span>Role</span><input disabled value={data?.admin?.role||''}/></label></div><div className="formActions"><button className="primarySmall" disabled={busy}>Save profile</button></div></form>
  <form className="panel formPanel" onSubmit={savePrefs}><div className="settingsTitle"><Settings/><div><h3>Interface preferences</h3><p>Stored per administrator.</p></div></div><div className="formGrid one"><label><span>Table density</span><select value={prefs.tableDensity||'comfortable'} onChange={e=>setPrefs({...prefs,tableDensity:e.target.value})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label><span>Timezone</span><input value={prefs.timezone||''} onChange={e=>setPrefs({...prefs,timezone:e.target.value})} placeholder="Asia/Karachi"/></label><label className="toggle"><input type="checkbox" checked={!!prefs.sidebarCollapsed} onChange={e=>setPrefs({...prefs,sidebarCollapsed:e.target.checked})}/><i/><span>Collapse sidebar by default</span></label><label><span>Additional preferences JSON</span><textarea className="jsonEditor" rows={7} value={prefs.preferences||'{}'} onChange={e=>setPrefs({...prefs,preferences:e.target.value})}/></label></div><div className="formActions"><button className="primarySmall" disabled={busy}>Save preferences</button></div></form>
 </div>
 <form className="panel formPanel globalSettingsPanel" onSubmit={saveGlobal}><div className="settingsTitle"><ShieldCheck/><div><h3>Global admin configuration</h3><p>SUPER_ADMIN only. These settings affect the admin console, not the mobile app feature flags.</p></div></div><div className="formGrid"><label><span>Support SLA hours</span><input type="number" min="1" value={global.support_sla_hours??24} onChange={e=>setGlobal({...global,support_sla_hours:Number(e.target.value)})}/></label><label><span>Session warning minutes</span><input type="number" min="1" value={global.session_warning_minutes??5} onChange={e=>setGlobal({...global,session_warning_minutes:Number(e.target.value)})}/></label><label><span>Default table page size</span><input type="number" min="10" max="200" value={global.default_page_size??50} onChange={e=>setGlobal({...global,default_page_size:Number(e.target.value)})}/></label><label className="toggle"><input type="checkbox" checked={!!global.maintenance_banner_enabled} onChange={e=>setGlobal({...global,maintenance_banner_enabled:e.target.checked})}/><i/><span>Admin maintenance banner</span></label><label style={{gridColumn:'1/-1'}}><span>Maintenance banner text</span><input value={global.maintenance_banner_text||''} onChange={e=>setGlobal({...global,maintenance_banner_text:e.target.value})}/></label></div><div className="formActions"><button className="primarySmall" disabled={busy}>Save global settings</button></div></form>
 </div>
}
