import {useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,CreditCard,RefreshCw,Search,Store,WalletCards} from 'lucide-react';
import {consoleApi} from '../consoleApi';
const d=(v:any)=>v?new Date(v).toLocaleString():'—';
const moneyStatus=(s:string)=>['active','verified','paid'].includes(String(s||'').toLowerCase())?'ok':'off';

export function BillingPage(){
 const[data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[store,setStore]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{setData(await consoleApi.billing({search,status:status||undefined,store:store||undefined}))}catch(e){setError(e instanceof Error?e.message:'Unable to load billing records')}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 if(selected)return <PurchaseDetail id={selected} back={()=>setSelected(null)} after={load}/>;
 const rows=data?.items||[];
 return <div className="modulePage">
  <div className="moduleHero"><div><p className="eyebrow">MODULE 11 · STORE BILLING OPERATIONS</p><h1>Billing & Purchases</h1><p>Review App Store / Google Play purchase records, verification state and entitlement linkage. Store transaction creation remains server/provider controlled.</p></div><button className="secondaryBtn" onClick={load}><RefreshCw/> Refresh</button></div>
  {error&&<div className="notice">{error}</div>}
  <div className="metricStrip"><Mini icon={<WalletCards/>} label="Purchases" value={data?.metrics?.total||0}/><Mini icon={<CheckCircle2/>} label="Verified / active" value={data?.metrics?.verified||0}/><Mini icon={<Store/>} label="Auto renew" value={data?.metrics?.autoRenew||0}/><Mini icon={<CreditCard/>} label="Needs review" value={data?.metrics?.needsReview||0}/></div>
  <div className="toolbar billingToolbar"><label className="tableSearch"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search email, product, transaction…"/><button className="textBtn" onClick={load}>Search</button></label><select value={store} onChange={e=>setStore(e.target.value)}><option value="">All stores</option><option value="apple">Apple</option><option value="google">Google</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="pending">Pending</option><option value="verified">Verified</option><option value="active">Active</option><option value="expired">Expired</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select><button className="secondaryBtn" onClick={load}>Apply</button></div>
  <div className="panel userPanel"><div className="utr billingRow uth"><span>User / Product</span><span>Store</span><span>Status</span><span>Plan</span><span>Purchased</span><span>Expires</span><span></span></div>
  {rows.length===0?<div className="emptyState"><CreditCard/><h3>No purchase records</h3><p>No purchases match the current filters.</p></div>:rows.map((x:any)=><div className="utr billingRow" key={x.id}><span className="userCell"><i>{String(x.store||'S')[0].toUpperCase()}</i><em><b>{x.email||x.user_id}</b><small>{x.product_id||'Unknown product'} · {x.transaction_id||'No transaction id'}</small></em></span><span>{x.store||'—'}</span><span><span className={'statusTag '+moneyStatus(x.status)}><i/>{x.status||'unknown'}</span></span><span>{x.plan_key||'—'}</span><span>{d(x.purchased_at||x.created_at)}</span><span>{d(x.expires_at)}</span><button className="iconBtn" onClick={()=>setSelected(x.id)}><CreditCard/></button></div>)}</div>
 </div>
}
function Mini({icon,label,value}:{icon:any;label:string;value:number}){return <div className="miniMetric diagnosticKpi"><span className="metricIcon">{icon}</span><div><span>{label}</span><b>{Number(value||0).toLocaleString()}</b></div></div>}

function PurchaseDetail({id,back,after}:{id:string;back:()=>void;after:()=>void}){
 const[data,setData]=useState<any>(null),[form,setForm]=useState<any>({}),[busy,setBusy]=useState(true),[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const x=await consoleApi.purchase(id);setData(x);setForm({status:x.purchase.status||'',planKey:x.purchase.plan_key||'',expiresAt:x.purchase.expires_at?String(x.purchase.expires_at).slice(0,16):'',autoRenew:!!x.purchase.auto_renew})}catch(e){setError(e instanceof Error?e.message:'Unable to load purchase')}finally{setBusy(false)}};
 useEffect(()=>{load()},[id]);
 const save=async()=>{setBusy(true);setError('');try{await consoleApi.updatePurchase(id,{status:form.status,planKey:form.planKey||null,expiresAt:form.expiresAt?new Date(form.expiresAt).toISOString():null,autoRenew:form.autoRenew});await load();await after()}catch(e){setError(e instanceof Error?e.message:'Unable to update purchase')}finally{setBusy(false)}};
 if(!data&&busy)return <div className="emptyState"><CreditCard/><h3>Loading purchase…</h3></div>;
 const p=data?.purchase||{};
 return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back to billing</button><div className="moduleHero"><div><p className="eyebrow">PURCHASE DETAIL</p><h1>{p.product_id||'Store purchase'}</h1><p>{data?.user?.email||p.user_id} · {p.store||'unknown store'}</p></div></div>{error&&<div className="notice">{error}</div>}
  <div className="detailGrid"><section className="panel"><h3>Store record</h3><Info k="Transaction ID" v={p.transaction_id}/><Info k="Original transaction" v={p.original_transaction_id}/><Info k="Purchased" v={d(p.purchased_at)}/><Info k="Last verified" v={d(p.last_verified_at)}/><Info k="Created" v={d(p.created_at)}/></section><section className="panel"><h3>Verification</h3><Info k="Status" v={p.status}/><Info k="Plan" v={p.plan_key}/><Info k="Expires" v={d(p.expires_at)}/><Info k="Auto renew" v={p.auto_renew?'Yes':'No'}/><Info k="Token stored" v={p.purchase_token_hash?'Hashed token present':'No token hash'}/></section></div>
  <section className="panel formPanel membershipEdit"><h3>Administrative correction</h3><p className="panelHint">Use only after provider/support verification. This does not create store transactions.</p><div className="formGrid"><label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="pending">Pending</option><option value="verified">Verified</option><option value="active">Active</option><option value="expired">Expired</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select></label><label><span>Plan key</span><input value={form.planKey} onChange={e=>setForm({...form,planKey:e.target.value})}/></label><label><span>Expires at</span><input type="datetime-local" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></label><label className="toggle"><input type="checkbox" checked={form.autoRenew} onChange={e=>setForm({...form,autoRenew:e.target.checked})}/><i/><span>Auto renew</span></label></div><div className="formActions"><button className="primarySmall" onClick={save} disabled={busy}><CheckCircle2/> Save correction</button></div></section>
 </div>
}
function Info({k,v}:{k:string;v:any}){return <div className="info"><small>{k}</small><span>{v??'—'}</span></div>}
