import {FormEvent,useEffect,useState} from 'react';
import {ArrowLeft,Edit3,Flag,Plus,RefreshCw,ShieldCheck,Trash2} from 'lucide-react';
import {consoleApi} from '../consoleApi';

export function FeatureFlagsPage(){
 const[data,setData]=useState<any>(null),[edit,setEdit]=useState<any>(null),[error,setError]=useState('');
 const load=async()=>{setError('');try{setData(await consoleApi.systemFlags())}catch(e){setError(e instanceof Error?e.message:'Unable to load flags')}};
 useEffect(()=>{load()},[]);
 if(edit)return <FlagEditor flag={edit==='new'?null:edit} back={()=>setEdit(null)} done={async()=>{setEdit(null);await load()}}/>;
 return <div className="modulePage"><div className="moduleHero"><div><p className="eyebrow">MODULE 16 · CONTROL PLANE</p><h1>Feature Flags</h1><p>Manage backend-controlled configuration values using the existing ul_system_flags schema. Public visibility is controlled with is_public; feature enablement can be represented inside the JSON value when required.</p></div><div className="actionRow"><button className="secondaryBtn" onClick={load}><RefreshCw/> Refresh</button><button className="primarySmall" onClick={()=>setEdit('new')}><Plus/> Add flag</button></div></div>{error&&<div className="notice">{error}</div>}
 <div className="flagGrid">{(data?.items||[]).map((x:any)=><div className="flagCard" key={x.key}><div className="flagTop"><span className="flagIcon"><Flag/></span><span className={'statusTag '+(x.is_public?'ok':'off')}><i/>{x.is_public?'Public':'Internal'}</span></div><h3>{x.key}</h3><p>{x.description||'No description'}</p><div className="flagValue"><small>Value</small><pre>{JSON.stringify(x.value,null,2)}</pre></div><footer><span>Updated {x.updated_at?new Date(x.updated_at).toLocaleString():'—'}</span><button className="iconBtn" onClick={()=>setEdit(x)}><Edit3/></button></footer></div>)}</div>{!(data?.items||[]).length&&<div className="panel emptyState"><Flag/><h3>No feature flags</h3><p>Create the first system flag when a backend-controlled switch is required.</p></div>}
 </div>
}
function FlagEditor({flag,back,done}:{flag:any;back:()=>void;done:()=>void}){
 const[form,setForm]=useState<any>({key:flag?.key||'',description:flag?.description||'',isPublic:flag?.is_public??false,value:JSON.stringify(flag?.value??{},null,2)}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{let value:any;try{value=JSON.parse(form.value||'{}')}catch{throw new Error('Value must be valid JSON')}const body={key:form.key,description:form.description,isPublic:form.isPublic,value};if(flag)await consoleApi.updateSystemFlag(flag.key,body);else await consoleApi.createSystemFlag(body);await done()}catch(e){setError(e instanceof Error?e.message:'Unable to save flag')}finally{setBusy(false)}};
 const remove=async()=>{if(!flag||!confirm(`Delete feature flag "${flag.key}"?`))return;setBusy(true);try{await consoleApi.deleteSystemFlag(flag.key);await done()}catch(e){setError(e instanceof Error?e.message:'Unable to delete flag')}finally{setBusy(false)}};
 return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back to flags</button><div className="moduleHero"><div><p className="eyebrow">{flag?'EDIT FEATURE FLAG':'ADD FEATURE FLAG'}</p><h1>{flag?flag.key:'Create system flag'}</h1><p>Use flags for non-secret backend/mobile configuration only. The existing table has key, value, description and is_public.</p></div>{flag&&<button className="dangerBtn" onClick={remove}><Trash2/> Delete</button>}</div>{error&&<div className="notice">{error}</div>}<form className="panel formPanel" onSubmit={submit}><div className="formGrid"><label><span>Key</span><input required disabled={!!flag} value={form.key} onChange={e=>setForm({...form,key:e.target.value.toLowerCase().replace(/[^a-z0-9_.-]/g,'')})}/></label><label className="toggle"><input type="checkbox" checked={form.isPublic} onChange={e=>setForm({...form,isPublic:e.target.checked})}/><i/><span>Public to client</span></label><label style={{gridColumn:'1/-1'}}><span>Description</span><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}><span>JSON value</span><textarea className="jsonEditor" rows={12} value={form.value} onChange={e=>setForm({...form,value:e.target.value})}/></label></div><div className="formActions"><button type="button" className="secondaryBtn" onClick={back}>Cancel</button><button className="primarySmall" disabled={busy}><ShieldCheck/> Save flag</button></div></form></div>
}
