import {FormEvent,useEffect,useMemo,useState} from 'react';
import {ArrowLeft,CheckCircle2,ChevronRight,Edit3,Plus,RefreshCw,Search,ShieldCheck,Sparkles,Users} from 'lucide-react';
import {consoleApi} from '../consoleApi';

export function MembershipPage(){
 const[tab,setTab]=useState<'plans'|'members'>('plans'),[plans,setPlans]=useState<any[]>([]),[members,setMembers]=useState<any[]>([]),[search,setSearch]=useState(''),[selected,setSelected]=useState<any>(null),[editing,setEditing]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');try{const[p,e]=await Promise.all([consoleApi.plans(),consoleApi.entitlements({search})]);setPlans(p.items||p||[]);setMembers(e.items||[])}catch(err){setError(err instanceof Error?err.message:'Unable to load membership data')}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const totals=useMemo(()=>({plans:plans.length,active:plans.filter(x=>x.is_active).length,members:members.length,pro:members.filter(x=>String(x.plan_key).toLowerCase()==='pro').length}),[plans,members]);
 if(editing)return <PlanEditor plan={editing==='new'?null:editing} cancel={()=>setEditing(null)} saved={async()=>{setEditing(null);await load()}}/>;
 if(selected?.kind==='plan')return <PlanDetail plan={selected.data} back={()=>setSelected(null)} edit={()=>setEditing(selected.data)} refreshed={async()=>{const p=await consoleApi.plan(selected.data.plan_key);setSelected({kind:'plan',data:p})}}/>;
 if(selected?.kind==='member')return <MemberDetail userId={selected.data.user_id} back={()=>setSelected(null)} refreshed={load}/>;
 return <div className="modulePage">
  <div className="moduleHero"><div><p className="eyebrow">MODULE 10 · MEMBERSHIP & ENTITLEMENTS</p><h1>Membership</h1><p>Manage plan catalog and individual user entitlements without changing the existing mobile database schema.</p></div><div className="actionRow"><button className="secondaryBtn" onClick={load}><RefreshCw/> Refresh</button><button className="primarySmall" onClick={()=>setEditing('new')}><Plus/> Add plan</button></div></div>
  {error&&<div className="notice">{error}</div>}
  <div className="metricStrip"><Mini label="Plans" value={totals.plans}/><Mini label="Active plans" value={totals.active}/><Mini label="Membership rows" value={totals.members}/><Mini label="Pro members" value={totals.pro}/></div>
  <div className="segmentTabs"><button className={tab==='plans'?'active':''} onClick={()=>setTab('plans')}><Sparkles/> Plan catalog</button><button className={tab==='members'?'active':''} onClick={()=>setTab('members')}><Users/> User entitlements</button></div>
  {tab==='plans'?<div className="planGrid">{plans.map(p=><button className="planCard" key={p.plan_key} onClick={()=>setSelected({kind:'plan',data:p})}><div className="planCardTop"><span className="planBadge">{p.plan_key}</span><span className={'statusTag '+(p.is_active?'ok':'off')}><i/>{p.is_active?'Active':'Inactive'}</span></div><h3>{p.name}</h3><p>{p.description||'No description'}</p><div className="entitlementPreview">{Object.entries(p.entitlements||{}).slice(0,4).map(([k,v])=><span key={k}><b>{pretty(k)}</b><small>{String(v)}</small></span>)}</div><footer><small>Sort {p.sort_order??0}</small><ChevronRight/></footer></button>)}</div>:
  <><div className="toolbar"><label className="tableSearch"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search email, name or user id"/><button className="textBtn" onClick={load}>Search</button></label></div><div className="panel userPanel"><div className="utr entitlementRow uth"><span>User</span><span>Plan</span><span>Status</span><span>Source</span><span>Expires</span><span></span></div>{members.length===0?<div className="emptyState"><Users/><h3>No entitlements</h3><p>No matching user membership records.</p></div>:members.map(m=><div className="utr entitlementRow" key={m.user_id}><span className="userCell"><i>{String(m.email||'U')[0].toUpperCase()}</i><em><b>{m.display_name||m.email||'User'}</b><small>{m.email||m.user_id}</small></em></span><span><span className="planBadge">{m.plan_key}</span></span><span><span className={'statusTag '+(m.status==='active'?'ok':'off')}><i/>{m.status}</span></span><span>{m.source||'—'}</span><span>{m.expires_at?new Date(m.expires_at).toLocaleDateString():'No expiry'}</span><button className="iconBtn" onClick={()=>setSelected({kind:'member',data:m})}><ChevronRight/></button></div>)}</div></>}
 </div>
}
function Mini({label,value}:{label:string;value:number}){return <div className="miniMetric"><span>{label}</span><b>{value.toLocaleString()}</b></div>}
function pretty(k:string){return k.replace(/_/g,' ').replace(/\b\w/g,x=>x.toUpperCase())}

function PlanDetail({plan,back,edit,refreshed}:{plan:any;back:()=>void;edit:()=>void;refreshed:()=>void}){
 const toggle=async()=>{await consoleApi.setPlanActive(plan.plan_key,!plan.is_active);await refreshed()};
 return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back to membership</button><div className="moduleHero"><div><p className="eyebrow">PLAN DETAIL</p><h1>{plan.name}</h1><p>{plan.description||'No description'}</p></div><div className="actionRow"><button className="secondaryBtn" onClick={toggle}>{plan.is_active?'Deactivate':'Activate'}</button><button className="primarySmall" onClick={edit}><Edit3/> Edit plan</button></div></div><div className="detailGrid"><section className="panel"><h3>Plan identity</h3><div className="info"><small>Key</small><span>{plan.plan_key}</span></div><div className="info"><small>Status</small><span>{plan.is_active?'Active':'Inactive'}</span></div><div className="info"><small>Sort order</small><span>{plan.sort_order??0}</span></div><div className="info"><small>Updated</small><span>{plan.updated_at?new Date(plan.updated_at).toLocaleString():'—'}</span></div></section><section className="panel"><h3>Entitlements</h3>{Object.entries(plan.entitlements||{}).map(([k,v])=><div className="info" key={k}><small>{pretty(k)}</small><span>{String(v)}</span></div>)}</section></div></div>
}

function PlanEditor({plan,cancel,saved}:{plan:any;cancel:()=>void;saved:()=>void}){
 const[form,setForm]=useState<any>({planKey:plan?.plan_key||'',name:plan?.name||'',description:plan?.description||'',sortOrder:plan?.sort_order??0,isActive:plan?.is_active??true,entitlements:JSON.stringify(plan?.entitlements||{},null,2)}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{let ent:any={};try{ent=JSON.parse(form.entitlements||'{}')}catch{throw new Error('Entitlements must be valid JSON')}const body={planKey:form.planKey,name:form.name,description:form.description,sortOrder:Number(form.sortOrder)||0,isActive:!!form.isActive,entitlements:ent};if(plan)await consoleApi.updatePlan(plan.plan_key,body);else await consoleApi.createPlan(body);await saved()}catch(err){setError(err instanceof Error?err.message:'Unable to save plan')}finally{setBusy(false)}};
 return <div className="modulePage"><button className="backLink" onClick={cancel}><ArrowLeft/> Cancel</button><div className="moduleHero"><div><p className="eyebrow">{plan?'EDIT PLAN':'ADD PLAN'}</p><h1>{plan?'Update membership plan':'Create membership plan'}</h1><p>Plan changes affect entitlement resolution used by the mobile/backend feature gates.</p></div></div>{error&&<div className="notice">{error}</div>}<form className="panel formPanel" onSubmit={submit}><div className="formGrid"><label><span>Plan key</span><input required disabled={!!plan} value={form.planKey} onChange={e=>setForm({...form,planKey:e.target.value.toLowerCase().replace(/[^a-z0-9_-]/g,'')})}/></label><label><span>Name</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}><span>Description</span><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label><span>Sort order</span><input type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:e.target.value})}/></label><label className="toggle"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/><i/><span>Active</span></label><label style={{gridColumn:'1/-1'}}><span>Entitlements JSON</span><textarea className="jsonEditor" rows={12} value={form.entitlements} onChange={e=>setForm({...form,entitlements:e.target.value})}/></label></div><div className="formActions"><button type="button" className="secondaryBtn" onClick={cancel}>Cancel</button><button className="primarySmall" disabled={busy}>{busy?'Saving…':'Save plan'}</button></div></form></div>
}

function MemberDetail({userId,back,refreshed}:{userId:string;back:()=>void;refreshed:()=>void}){
 const[data,setData]=useState<any>(null),[plans,setPlans]=useState<any[]>([]),[form,setForm]=useState<any>({}),[busy,setBusy]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const[d,p]=await Promise.all([consoleApi.entitlement(userId),consoleApi.plans()]);setData(d);setPlans(p.items||p||[]);setForm({planKey:d.entitlement?.plan_key||'free',status:d.entitlement?.status||'active',source:d.entitlement?.source||'admin',expiresAt:d.entitlement?.expires_at?String(d.entitlement.expires_at).slice(0,16):'',override:JSON.stringify(d.entitlement?.entitlements_override||{},null,2)})}catch(e){setError(e instanceof Error?e.message:'Unable to load member')}finally{setBusy(false)}})()},[userId]);
 const save=async()=>{setBusy(true);setError('');try{let override={};try{override=JSON.parse(form.override||'{}')}catch{throw new Error('Override JSON is invalid')}await consoleApi.updateEntitlement(userId,{planKey:form.planKey,status:form.status,source:form.source,expiresAt:form.expiresAt?new Date(form.expiresAt).toISOString():null,entitlementsOverride:override});const d=await consoleApi.entitlement(userId);setData(d);await refreshed()}catch(e){setError(e instanceof Error?e.message:'Unable to update entitlement')}finally{setBusy(false)}};
 if(busy&&!data)return <div className="emptyState"><ShieldCheck/><h3>Loading membership…</h3></div>;
 return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back to entitlements</button><div className="moduleHero"><div><p className="eyebrow">USER ENTITLEMENT DETAIL</p><h1>{data?.user?.display_name||data?.user?.email||userId}</h1><p>{data?.user?.email||userId}</p></div></div>{error&&<div className="notice">{error}</div>}<div className="detailGrid"><section className="panel"><h3>Current membership</h3><div className="info"><small>Plan</small><span>{data?.entitlement?.plan_key||'free'}</span></div><div className="info"><small>Status</small><span>{data?.entitlement?.status||'active'}</span></div><div className="info"><small>Source</small><span>{data?.entitlement?.source||'system'}</span></div><div className="info"><small>Expires</small><span>{data?.entitlement?.expires_at?new Date(data.entitlement.expires_at).toLocaleString():'No expiry'}</span></div></section><section className="panel"><h3>Effective plan entitlements</h3>{Object.entries(data?.plan?.entitlements||{}).map(([k,v])=><div className="info" key={k}><small>{pretty(k)}</small><span>{String(v)}</span></div>)}</section></div><section className="panel formPanel membershipEdit"><h3>Edit user membership</h3><div className="formGrid"><label><span>Plan</span><select value={form.planKey||''} onChange={e=>setForm({...form,planKey:e.target.value})}>{plans.map(p=><option key={p.plan_key} value={p.plan_key}>{p.name}</option>)}</select></label><label><span>Status</span><select value={form.status||'active'} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="grace">Grace</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></select></label><label><span>Source</span><input value={form.source||''} onChange={e=>setForm({...form,source:e.target.value})}/></label><label><span>Expires at</span><input type="datetime-local" value={form.expiresAt||''} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}><span>Entitlements override JSON</span><textarea className="jsonEditor" rows={8} value={form.override||'{}'} onChange={e=>setForm({...form,override:e.target.value})}/></label></div><div className="formActions"><button className="primarySmall" onClick={save} disabled={busy}><CheckCircle2/> Save entitlement</button></div></section></div>
}
