import {FormEvent,useEffect,useState} from 'react';
import {AlertTriangle,ArrowLeft,CheckCircle2,Eye,Plus,RefreshCw,Search,ShieldAlert,ShieldCheck,UserX} from 'lucide-react';
import {consoleApi} from '../consoleApi';

export function ModerationPage(){
 const[data,setData]=useState<any>(null),[detail,setDetail]=useState<string|null>(null),[create,setCreate]=useState(false),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[severity,setSeverity]=useState(''),[error,setError]=useState('');
 const load=async()=>{setError('');try{setData(await consoleApi.moderation({search,status:status||undefined,severity:severity||undefined}))}catch(e){setError(e instanceof Error?e.message:'Unable to load moderation cases')}};
 useEffect(()=>{load()},[]);
 if(create)return <CreateCase back={()=>setCreate(false)} done={async()=>{setCreate(false);await load()}}/>;
 if(detail)return <CaseDetail id={detail} back={()=>setDetail(null)} after={load}/>;
 return <div className="modulePage">
  <div className="moduleHero"><div><p className="eyebrow">MODULE 14 · TRUST & SAFETY</p><h1>Moderation & Abuse</h1><p>Operational case queue for reported users, streams and destinations. Administrative actions are explicit, auditable and do not silently alter mobile schemas.</p></div><div className="actionRow"><button className="secondaryBtn" onClick={load}><RefreshCw/> Refresh</button><button className="primarySmall" onClick={()=>setCreate(true)}><Plus/> Open case</button></div></div>
  {error&&<div className="notice">{error}</div>}
  <div className="metricStrip"><Mini label="Open" value={data?.metrics?.open||0}/><Mini label="Investigating" value={data?.metrics?.investigating||0}/><Mini label="High / critical" value={data?.metrics?.high||0}/><Mini label="Resolved" value={data?.metrics?.resolved||0}/></div>
  <div className="toolbar supportToolbar"><label className="tableSearch"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search subject, target, reason…"/><button className="textBtn" onClick={load}>Search</button></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="open">Open</option><option value="investigating">Investigating</option><option value="actioned">Actioned</option><option value="dismissed">Dismissed</option><option value="resolved">Resolved</option></select><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All severity</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select><button className="secondaryBtn" onClick={load}>Apply</button></div>
  <div className="panel userPanel"><div className="utr moderationRow uth"><span>Case</span><span>Target</span><span>Status</span><span>Severity</span><span>Updated</span><span></span></div>{(data?.items||[]).length===0?<div className="emptyState"><ShieldCheck/><h3>No moderation cases</h3><p>No cases match current filters.</p></div>:(data.items||[]).map((x:any)=><div className="utr moderationRow" key={x.id}><span><b>{x.subject}</b><small>{x.reason||'No reason supplied'}</small></span><span><b>{x.target_type}</b><small>{x.target_label||x.target_id}</small></span><span><span className={'statusTag '+(['resolved','dismissed'].includes(x.status)?'ok':'off')}><i/>{x.status}</span></span><span><span className={'severity '+(x.severity==='critical'?'error':x.severity==='high'?'warning':'info')}>{x.severity}</span></span><span>{new Date(x.updated_at||x.created_at).toLocaleString()}</span><button className="iconBtn" onClick={()=>setDetail(x.id)}><Eye/></button></div>)}</div>
 </div>
}
function Mini({label,value}:{label:string;value:number}){return <div className="miniMetric"><span>{label}</span><b>{Number(value||0).toLocaleString()}</b></div>}
function CreateCase({back,done}:{back:()=>void;done:()=>void}){
 const[form,setForm]=useState<any>({targetType:'user',targetId:'',subject:'',reason:'',severity:'medium',notes:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await consoleApi.createModerationCase(form);await done()}catch(e){setError(e instanceof Error?e.message:'Unable to create case')}finally{setBusy(false)}};
 return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Cancel</button><div className="moduleHero"><div><p className="eyebrow">OPEN MODERATION CASE</p><h1>Create investigation case</h1><p>Target can be an existing user, broadcast session, or streaming connection.</p></div></div>{error&&<div className="notice">{error}</div>}<form className="panel formPanel" onSubmit={submit}><div className="formGrid"><label><span>Target type</span><select value={form.targetType} onChange={e=>setForm({...form,targetType:e.target.value})}><option value="user">User</option><option value="stream">Stream</option><option value="connection">Connection</option></select></label><label><span>Target UUID</span><input required value={form.targetId} onChange={e=>setForm({...form,targetId:e.target.value})}/></label><label><span>Severity</span><select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label style={{gridColumn:'1/-1'}}><span>Subject</span><input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}><span>Reason</span><textarea rows={4} required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}><span>Internal notes</span><textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="formActions"><button type="button" className="secondaryBtn" onClick={back}>Cancel</button><button className="primarySmall" disabled={busy}><ShieldAlert/> Open case</button></div></form></div>
}
function CaseDetail({id,back,after}:{id:string;back:()=>void;after:()=>void}){
 const[data,setData]=useState<any>(null),[form,setForm]=useState<any>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{const x=await consoleApi.moderationCase(id);setData(x);setForm({status:x.case.status,severity:x.case.severity,resolution:x.case.resolution||'',notes:x.case.notes||'',action:x.case.action||'none'})}catch(e){setError(e instanceof Error?e.message:'Unable to load case')}};
 useEffect(()=>{load()},[id]);
 const save=async()=>{setBusy(true);setError('');try{await consoleApi.updateModerationCase(id,form);await load();await after()}catch(e){setError(e instanceof Error?e.message:'Unable to update case')}finally{setBusy(false)}};
 if(!data)return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back</button>{error?<div className="notice">{error}</div>:<div className="emptyState"><ShieldAlert/><h3>Loading case…</h3></div>}</div>;
 const c=data.case;
 return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back to moderation</button><div className="moduleHero"><div><p className="eyebrow">MODERATION CASE DETAIL</p><h1>{c.subject}</h1><p>{c.target_type} · {data.target?.label||c.target_id}</p></div></div>{error&&<div className="notice">{error}</div>}<div className="detailGrid"><section className="panel"><h3>Case evidence</h3><Info k="Reason" v={c.reason}/><Info k="Opened" v={new Date(c.created_at).toLocaleString()}/><Info k="Opened by" v={c.created_by_admin_id}/><Info k="Target" v={data.target?.label||c.target_id}/><div className="jsonBlock">{JSON.stringify(c.evidence||{},null,2)}</div></section><section className="panel formPanel"><h3>Decision</h3><div className="formGrid one"><label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="open">Open</option><option value="investigating">Investigating</option><option value="actioned">Actioned</option><option value="dismissed">Dismissed</option><option value="resolved">Resolved</option></select></label><label><span>Severity</span><select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label><label><span>Action</span><select value={form.action} onChange={e=>setForm({...form,action:e.target.value})}><option value="none">No platform action</option><option value="disable_user">Disable user</option><option value="enable_user">Re-enable user</option><option value="disable_connection">Disable connection</option><option value="end_stream">End stream</option></select></label><label><span>Resolution</span><textarea rows={4} value={form.resolution} onChange={e=>setForm({...form,resolution:e.target.value})}/></label><label><span>Internal notes</span><textarea rows={5} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><button className="primarySmall" onClick={save} disabled={busy}><CheckCircle2/> Save decision</button></section></div></div>
}
function Info({k,v}:{k:string;v:any}){return <div className="info"><small>{k}</small><span>{v??'—'}</span></div>}
