import {FormEvent,useEffect,useState} from 'react';
import {ArrowLeft,Bell,Send,Trash2} from 'lucide-react';
import {consoleApi} from '../consoleApi';

export function NotificationsPage(){
 const[data,setData]=useState<any>(null),[detail,setDetail]=useState<any>(null),[compose,setCompose]=useState(false),[filter,setFilter]=useState(''),[error,setError]=useState('');
 const load=async()=>{setError('');try{setData(await consoleApi.notifications({severity:filter||undefined}))}catch(e){setError(e instanceof Error?e.message:'Unable to load notifications')}};
 useEffect(()=>{load()},[]);
 if(compose)return <Compose close={()=>setCompose(false)} sent={async()=>{setCompose(false);await load()}}/>;
 if(detail)return <NotificationDetail id={detail} back={()=>setDetail(null)} deleted={async()=>{setDetail(null);await load()}}/>;
 return <div className="modulePage"><div className="moduleHero"><div><p className="eyebrow">MODULE 12 · USER COMMUNICATIONS</p><h1>Notifications</h1><p>Send in-app notices to one user or the full user base, then inspect notification and push delivery state.</p></div><button className="primarySmall" onClick={()=>setCompose(true)}><Send/> Compose notification</button></div>{error&&<div className="notice">{error}</div>}
  <div className="metricStrip"><Mini label="Notifications" value={data?.metrics?.total||0}/><Mini label="Unread" value={data?.metrics?.unread||0}/><Mini label="Push queued" value={data?.metrics?.pushQueued||0}/><Mini label="Push failed" value={data?.metrics?.pushFailed||0}/></div>
  <div className="toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All severities</option><option value="info">Info</option><option value="success">Success</option><option value="warning">Warning</option><option value="error">Error</option></select><button className="secondaryBtn" onClick={load}>Apply</button></div>
  <div className="panel userPanel"><div className="utr notificationRow uth"><span>Notification</span><span>User</span><span>Severity</span><span>Read</span><span>Created</span><span></span></div>{(data?.items||[]).length===0?<div className="emptyState"><Bell/><h3>No notifications</h3><p>No matching notification rows.</p></div>:(data.items||[]).map((x:any)=><div className="utr notificationRow" key={x.id}><span><b>{x.title}</b><small>{x.body}</small></span><span>{x.email||x.user_id}</span><span><span className={'severity '+x.severity}>{x.severity}</span></span><span>{x.read_at?'Read':'Unread'}</span><span>{new Date(x.created_at).toLocaleString()}</span><button className="iconBtn" onClick={()=>setDetail(x.id)}><Bell/></button></div>)}</div>
 </div>
}
function Mini({label,value}:{label:string;value:number}){return <div className="miniMetric"><span>{label}</span><b>{Number(value||0).toLocaleString()}</b></div>}

function Compose({close,sent}:{close:()=>void;sent:()=>void}){
 const[form,setForm]=useState<any>({audience:'user',userId:'',type:'admin_message',title:'',body:'',severity:'info',actionType:'',push:true}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await consoleApi.sendNotification(form);await sent()}catch(e){setError(e instanceof Error?e.message:'Unable to send notification')}finally{setBusy(false)}};
 return <div className="modulePage"><button className="backLink" onClick={close}><ArrowLeft/> Cancel</button><div className="moduleHero"><div><p className="eyebrow">COMPOSE NOTIFICATION</p><h1>Send user communication</h1><p>Broadcast sends one notification per current authentication user. Push deliveries are queued only for registered device rows.</p></div></div>{error&&<div className="notice">{error}</div>}<form className="panel formPanel" onSubmit={submit}><div className="formGrid"><label><span>Audience</span><select value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option value="user">Single user</option><option value="all">All users</option></select></label>{form.audience==='user'&&<label><span>User UUID</span><input required value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})} placeholder="Existing mobile user UUID"/></label>}<label><span>Type</span><input required value={form.type} onChange={e=>setForm({...form,type:e.target.value})}/></label><label><span>Severity</span><select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option value="info">Info</option><option value="success">Success</option><option value="warning">Warning</option><option value="error">Error</option></select></label><label style={{gridColumn:'1/-1'}}><span>Title</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}><span>Body</span><textarea rows={5} required value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><label><span>Action type (optional)</span><input value={form.actionType} onChange={e=>setForm({...form,actionType:e.target.value})}/></label><label className="toggle"><input type="checkbox" checked={form.push} onChange={e=>setForm({...form,push:e.target.checked})}/><i/><span>Queue push delivery</span></label></div><div className="formActions"><button type="button" className="secondaryBtn" onClick={close}>Cancel</button><button className="primarySmall" disabled={busy}><Send/> {busy?'Sending…':'Send notification'}</button></div></form></div>
}

function NotificationDetail({id,back,deleted}:{id:string;back:()=>void;deleted:()=>void}){
 const[data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{consoleApi.notification(id).then(setData).catch((e:unknown)=>setError(e instanceof Error?e.message:'Unable to load notification'))},[id]);
 const remove=async()=>{if(!confirm('Delete this notification and its push delivery rows?'))return;await consoleApi.deleteNotification(id);await deleted()};
 if(!data)return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back</button>{error?<div className="notice">{error}</div>:<div className="emptyState"><Bell/><h3>Loading notification…</h3></div>}</div>;
 const n=data.notification;
 return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back to notifications</button><div className="moduleHero"><div><p className="eyebrow">NOTIFICATION DETAIL</p><h1>{n.title}</h1><p>{data.user?.email||n.user_id}</p></div><button className="dangerBtn" onClick={remove}><Trash2/> Delete</button></div><div className="detailGrid"><section className="panel"><h3>Message</h3><Info k="Type" v={n.type}/><Info k="Severity" v={n.severity}/><Info k="Body" v={n.body}/><Info k="Read at" v={n.read_at?new Date(n.read_at).toLocaleString():'Unread'}/><Info k="Created" v={new Date(n.created_at).toLocaleString()}/></section><section className="panel"><h3>Action</h3><Info k="Action type" v={n.action_type}/><div className="jsonBlock">{JSON.stringify(n.action_payload||{},null,2)}</div></section></div><section className="panel"><div className="panelHead"><div><h3>Push deliveries</h3><p>Device-level delivery queue/state</p></div></div>{(data.deliveries||[]).length?(data.deliveries||[]).map((x:any)=><div className="recordLine" key={x.id}><span><b>{x.provider||'Push provider'}</b><small>{x.status} · {x.error_code||''} {x.error_message||''}</small></span><span>{x.sent_at?new Date(x.sent_at).toLocaleString():new Date(x.created_at).toLocaleString()}</span></div>):<div className="emptyRow">No push delivery rows</div>}</section></div>
}
function Info({k,v}:{k:string;v:any}){return <div className="info"><small>{k}</small><span>{v??'—'}</span></div>}
