import {FormEvent,useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,LifeBuoy,MessageSquare,Plus,RefreshCw,Search,Send} from 'lucide-react';
import {consoleApi} from '../consoleApi';

export function SupportPage(){
 const[data,setData]=useState<any>(null),[detail,setDetail]=useState<string|null>(null),[create,setCreate]=useState(false),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[priority,setPriority]=useState(''),[error,setError]=useState('');
 const load=async()=>{setError('');try{setData(await consoleApi.supportTickets({search,status:status||undefined,priority:priority||undefined}))}catch(e){setError(e instanceof Error?e.message:'Unable to load support tickets')}};
 useEffect(()=>{load()},[]);
 if(create)return <CreateTicket back={()=>setCreate(false)} created={async()=>{setCreate(false);await load()}}/>;
 if(detail)return <TicketDetail id={detail} back={()=>setDetail(null)} after={load}/>;
 return <div className="modulePage"><div className="moduleHero"><div><p className="eyebrow">MODULE 13 · SUPPORT OPERATIONS</p><h1>Support Tickets</h1><p>Manage user requests, diagnostics, priority, lifecycle and threaded responses from one operational queue.</p></div><div className="actionRow"><button className="secondaryBtn" onClick={load}><RefreshCw/> Refresh</button><button className="primarySmall" onClick={()=>setCreate(true)}><Plus/> Create ticket</button></div></div>{error&&<div className="notice">{error}</div>}
 <div className="metricStrip"><Mini label="Open" value={data?.metrics?.open||0}/><Mini label="In progress" value={data?.metrics?.inProgress||0}/><Mini label="Urgent / high" value={data?.metrics?.high||0}/><Mini label="Resolved / closed" value={data?.metrics?.closed||0}/></div>
 <div className="toolbar supportToolbar"><label className="tableSearch"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search subject, category, user…"/><button className="textBtn" onClick={load}>Search</button></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting_user">Waiting user</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">All priorities</option><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><button className="secondaryBtn" onClick={load}>Apply</button></div>
 <div className="panel userPanel"><div className="utr supportRow uth"><span>Ticket</span><span>User</span><span>Status</span><span>Priority</span><span>Updated</span><span></span></div>{(data?.items||[]).length===0?<div className="emptyState"><LifeBuoy/><h3>No support tickets</h3><p>No tickets match current filters.</p></div>:(data.items||[]).map((x:any)=><div className="utr supportRow" key={x.id}><span><b>{x.subject}</b><small>{x.category} · {x.description}</small></span><span>{x.email||x.user_id}</span><span><span className={'statusTag '+(['resolved','closed'].includes(x.status)?'ok':'off')}><i/>{x.status}</span></span><span><span className={'severity '+(x.priority==='urgent'?'error':x.priority==='high'?'warning':'info')}>{x.priority}</span></span><span>{new Date(x.updated_at||x.created_at).toLocaleString()}</span><button className="iconBtn" onClick={()=>setDetail(x.id)}><MessageSquare/></button></div>)}</div>
 </div>
}
function Mini({label,value}:{label:string;value:number}){return <div className="miniMetric"><span>{label}</span><b>{Number(value||0).toLocaleString()}</b></div>}

function CreateTicket({back,created}:{back:()=>void;created:()=>void}){
 const[form,setForm]=useState<any>({userId:'',category:'account',subject:'',description:'',priority:'normal'}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await consoleApi.createSupportTicket(form);await created()}catch(e){setError(e instanceof Error?e.message:'Unable to create ticket')}finally{setBusy(false)}};
 return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Cancel</button><div className="moduleHero"><div><p className="eyebrow">CREATE SUPPORT TICKET</p><h1>Open a ticket for a user</h1><p>Use an existing mobile user UUID. The ticket will appear in the user’s support history.</p></div></div>{error&&<div className="notice">{error}</div>}<form className="panel formPanel" onSubmit={submit}><div className="formGrid"><label><span>User UUID</span><input required value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})}/></label><label><span>Category</span><input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label><span>Priority</span><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label style={{gridColumn:'1/-1'}}><span>Subject</span><input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}><span>Description</span><textarea rows={6} required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><div className="formActions"><button type="button" className="secondaryBtn" onClick={back}>Cancel</button><button className="primarySmall" disabled={busy}><Plus/> Create ticket</button></div></form></div>
}

function TicketDetail({id,back,after}:{id:string;back:()=>void;after:()=>void}){
 const[data,setData]=useState<any>(null),[form,setForm]=useState<any>({}),[reply,setReply]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{const x=await consoleApi.supportTicket(id);setData(x);setForm({status:x.ticket.status,priority:x.ticket.priority})}catch(e){setError(e instanceof Error?e.message:'Unable to load ticket')}};
 useEffect(()=>{load()},[id]);
 const save=async()=>{setBusy(true);setError('');try{await consoleApi.updateSupportTicket(id,form);await load();await after()}catch(e){setError(e instanceof Error?e.message:'Unable to update ticket')}finally{setBusy(false)}};
 const send=async()=>{if(!reply.trim())return;setBusy(true);setError('');try{await consoleApi.replySupportTicket(id,reply.trim());setReply('');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to send reply')}finally{setBusy(false)}};
 if(!data)return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back</button>{error?<div className="notice">{error}</div>:<div className="emptyState"><LifeBuoy/><h3>Loading ticket…</h3></div>}</div>;
 const t=data.ticket;
 return <div className="modulePage"><button className="backLink" onClick={back}><ArrowLeft/> Back to tickets</button><div className="moduleHero"><div><p className="eyebrow">SUPPORT TICKET DETAIL</p><h1>{t.subject}</h1><p>{data.user?.email||t.user_id} · {t.category}</p></div></div>{error&&<div className="notice">{error}</div>}
 <div className="supportDetailGrid"><section className="panel"><h3>Request</h3><p className="supportDescription">{t.description}</p><div className="info"><small>Created</small><span>{new Date(t.created_at).toLocaleString()}</span></div><div className="info"><small>Closed</small><span>{t.closed_at?new Date(t.closed_at).toLocaleString():'—'}</span></div><h4>Diagnostics</h4><div className="jsonBlock">{JSON.stringify(t.diagnostics||{},null,2)}</div></section><section className="panel formPanel"><h3>Manage ticket</h3><div className="formGrid one"><label><span>Status</span><select value={form.status||''} onChange={e=>setForm({...form,status:e.target.value})}><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting_user">Waiting user</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></label><label><span>Priority</span><select value={form.priority||''} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></div><button className="primarySmall" onClick={save} disabled={busy}><CheckCircle2/> Save ticket state</button></section></div>
 <section className="panel supportThread"><div className="panelHead"><div><h3>Conversation</h3><p>User and admin replies in chronological order</p></div></div><div className="thread">{(data.messages||[]).map((m:any)=><div className={'bubble '+(m.sender_type==='admin'?'admin':'user')} key={m.id}><div><b>{m.sender_type==='admin'?'Universal Live Support':'User'}</b><small>{new Date(m.created_at).toLocaleString()}</small></div><p>{m.message}</p></div>)}{!(data.messages||[]).length&&<div className="emptyRow">No replies yet</div>}</div><div className="replyBox"><textarea rows={4} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a support response…"/><button className="primarySmall" onClick={send} disabled={busy||!reply.trim()}><Send/> Send reply</button></div></section>
 </div>
}
