import {BadRequestException,Injectable,UnauthorizedException} from '@nestjs/common';
import {ConfigService} from '@nestjs/config';
import {JwtService} from '@nestjs/jwt';
import * as bcrypt from 'bcryptjs';
import {createHash,randomBytes,randomInt} from 'crypto';
import {SupabaseService} from '../supabase/supabase.service';
@Injectable() export class AdminAuthService{
 constructor(private db:SupabaseService,private jwt:JwtService,private cfg:ConfigService){}
 private secret(){const x=this.cfg.get<string>('ADMIN_JWT_SECRET')||this.cfg.get<string>('JWT_ACCESS_SECRET');if(!x||x.length<32)throw new Error('Admin JWT secret is not configured; set ADMIN_JWT_SECRET or JWT_ACCESS_SECRET to at least 32 characters');return x}
 private hash(v:string){return createHash('sha256').update(v).digest('hex')}
 private async row(email:string){const {data,error}=await this.db.admin.from('ul_admin_users').select('*').eq('email',email.trim().toLowerCase()).maybeSingle();if(error)throw new Error(`Admin account store unavailable: ${error.message}`);return data as any}
 publicAdmin(a:any){return {id:a.id,email:a.email,displayName:a.display_name,role:a.role,permissions:a.permissions||[]}}
 private async issue(a:any){const accessToken=await this.jwt.signAsync({sub:a.id,email:a.email,role:a.role,type:'admin-access'},{secret:this.secret(),expiresIn:'15m'});const refreshToken=randomBytes(48).toString('base64url');await this.db.admin.from('ul_admin_refresh_tokens').insert({admin_user_id:a.id,token_hash:this.hash(refreshToken),expires_at:new Date(Date.now()+30*864e5).toISOString()});return {accessToken,refreshToken,expiresIn:900,admin:this.publicAdmin(a)}}
 async login(email:string,password:string){const a=await this.row(email);if(!a||!a.is_active)throw new UnauthorizedException('Invalid admin email or password');if(a.locked_until&&new Date(a.locked_until)>new Date())throw new UnauthorizedException('Admin account is temporarily locked');const ok=await bcrypt.compare(password,a.password_hash);if(!ok){const n=(a.failed_login_count||0)+1;await this.db.admin.from('ul_admin_users').update({failed_login_count:n,locked_until:n>=5?new Date(Date.now()+15*60e3).toISOString():null}).eq('id',a.id);throw new UnauthorizedException('Invalid admin email or password')}await this.db.admin.from('ul_admin_users').update({failed_login_count:0,locked_until:null,last_login_at:new Date().toISOString()}).eq('id',a.id);await this.audit(a.id,'auth.login');return this.issue(a)}
 async verifyAccess(token:string){try{const p:any=await this.jwt.verifyAsync(token,{secret:this.secret()});if(p.type!=='admin-access')throw 0;const {data:a}=await this.db.admin.from('ul_admin_users').select('*').eq('id',p.sub).eq('is_active',true).single();if(!a)throw 0;return {...a,sub:a.id}}catch{throw new UnauthorizedException('Admin session expired or invalid')}}
 async refresh(token:string){const h=this.hash(token);const {data:r}=await this.db.admin.from('ul_admin_refresh_tokens').select('*').eq('token_hash',h).is('revoked_at',null).gt('expires_at',new Date().toISOString()).maybeSingle();if(!r)throw new UnauthorizedException('Refresh token invalid');await this.db.admin.from('ul_admin_refresh_tokens').update({revoked_at:new Date().toISOString()}).eq('id',r.id);const {data:a}=await this.db.admin.from('ul_admin_users').select('*').eq('id',r.admin_user_id).eq('is_active',true).single();if(!a)throw new UnauthorizedException('Admin disabled');return this.issue(a)}
 async forgot(email:string){const a=await this.row(email);if(a&&a.is_active){const code=String(randomInt(100000,1000000));await this.db.admin.from('ul_admin_otp_codes').update({consumed_at:new Date().toISOString()}).eq('admin_user_id',a.id).is('consumed_at',null);await this.db.admin.from('ul_admin_otp_codes').insert({admin_user_id:a.id,purpose:'password_reset',code_hash:await bcrypt.hash(code,10),expires_at:new Date(Date.now()+10*60e3).toISOString()});console.log(`[DEV ADMIN OTP] ${a.email}: ${code}`);/* Development fallback only; production password-reset delivery should use the configured mail transport. */}return {ok:true}}
 async verifyResetOtp(email:string,code:string){const a=await this.row(email);if(!a)throw new BadRequestException('Invalid or expired code');const {data:o}=await this.db.admin.from('ul_admin_otp_codes').select('*').eq('admin_user_id',a.id).eq('purpose','password_reset').is('consumed_at',null).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!o||o.attempts>=5||!(await bcrypt.compare(code,o.code_hash))){if(o)await this.db.admin.from('ul_admin_otp_codes').update({attempts:(o.attempts||0)+1}).eq('id',o.id);throw new BadRequestException('Invalid or expired code')}await this.db.admin.from('ul_admin_otp_codes').update({consumed_at:new Date().toISOString()}).eq('id',o.id);const resetToken=await this.jwt.signAsync({sub:a.id,type:'admin-reset'},{secret:this.secret(),expiresIn:'10m'});return {resetToken}}
 async resetPassword(token:string,password:string){if(!password||password.length<10)throw new BadRequestException('Password must be at least 10 characters');let p:any;try{p=await this.jwt.verifyAsync(token,{secret:this.secret()})}catch{throw new BadRequestException('Reset token expired')}if(p.type!=='admin-reset')throw new BadRequestException('Invalid reset token');await this.db.admin.from('ul_admin_users').update({password_hash:await bcrypt.hash(password,12),failed_login_count:0,locked_until:null}).eq('id',p.sub);await this.db.admin.from('ul_admin_refresh_tokens').update({revoked_at:new Date().toISOString()}).eq('admin_user_id',p.sub).is('revoked_at',null);await this.audit(p.sub,'auth.password_reset');return {ok:true}}
 async logout(id:string,refresh:string){await this.db.admin.from('ul_admin_refresh_tokens').update({revoked_at:new Date().toISOString()}).eq('admin_user_id',id).eq('token_hash',this.hash(refresh)).is('revoked_at',null);await this.audit(id,'auth.logout');return {ok:true}}
 private async audit(id:string,action:string){await this.db.admin.from('ul_admin_audit_log').insert({admin_user_id:id,action})}
}
